DeveloperAcademy-POSTECH/MC2-Team8-Ssok

.gitignore
MC2-Snack/MC2-Snack.xcodeproj/project.pbxproj
MC2-Snack/MC2-Snack.xcodeproj/project.xcworkspace/contents.xcworkspacedata
MC2-Snack/MC2-Snack.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
MC2-Snack/MC2-Snack/Assets.xcassets/AccentColor.colorset/Contents.json
MC2-Snack/MC2-Snack/Assets.xcassets/AppIcon.appiconset/Contents.json
MC2-Snack/MC2-Snack/Assets.xcassets/Contents.json
MC2-Snack/MC2-Snack/Assets.xcassets/bg.colorset/Contents.json
MC2-Snack/MC2-Snack/ContentView.swift
MC2-Snack/MC2-Snack/MC2_SnackApp.swift
MC2-Snack/MC2-Snack/Preview Content/Preview Assets.xcassets/Contents.json

Snack 잘했어요

---

Ssok/Global/Extension/View+.swift
Ssok/Model/Who.swift
Ssok/Views/AddMemberView.swift
Ssok/Views/StrawView.swift

- add filtered recommendation
- korean particle formatter(comment out)

feature: add filtered recommendation, korean particle formatter(comment out)

---

Ssok.xcodeproj/project.pbxproj
Ssok/Global/Extension/View+.swift

feature: add change english name function

feature: add change english name function

---

Ssok/Assets.xcassets/finaldrink.imageset/Contents.json
Ssok/Views/EndingView.swift
Ssok/Views/StrawView.swift

프리뷰 크래쉬 수정 완료
(대신 프리뷰에선 who 안 떠여 빌드하면 잘 떠여)

fix: fix preview crash error

---

Ssok/Views/BallView.swift
Ssok/Views/StrawView.swift

fix: fix ball animation(jjo taste)

fix: fix ball animation(jjo taste)

---

Ssok.xcodeproj/project.pbxproj
Ssok/Views/IntroView.swift

fix : Introview animation error.

fix : IntroView Animation Issue

---

Ssok/ViewModel/AddMemberViewModel.swift
Ssok/Views/AddMemberView.swift

- 키보드가 올라와 있는 상태에서 뷰의 다른 부분을 탭했을 때 키보드가 숨겨지도록

feature: keyboard dismiss when view tapped

---

Ssok.xcodeproj/project.pbxproj
Ssok/Assets.xcassets/Colors/MissionOrangeBorder.colorset/Contents.json
Ssok/Assets.xcassets/Colors/MissonOrange.colorset/Contents.json
Ssok/Views/MissonDecibelView.swift
Ssok/Views/Recycle/MissionTitleView.swift
Ssok/Views/Recycle/MissonTitleView.swift

feature: add recycle mission titleView

---

Ssok.xcodeproj/project.pbxproj
Ssok/Assets.xcassets/Colors/GoalRed.colorset/Contents.json
Ssok/Assets.xcassets/Colors/MissionPurple.colorset/Contents.json
Ssok/Views/MissionDecibelView.swift
Ssok/Views/MissionPedometerView.swift
Ssok/Views/Recycle/CircularProgressView.swift
Ssok/Views/Recycle/WhiteRectangleView.swift
Ssok/_BubblesApp.swift

set decibel, pedometer view layout

feature: set decibel, pedometer view layout

---

Ssok.xcodeproj/project.pbxproj
Ssok/AppDelegate.swift
Ssok/Model/ARModel.swift
Ssok/ViewModel/ARViewModel.swift
Ssok/Views/SmileView.swift

feature: Update eyeblink and smile View .... ussage( SmileView(ARstate: "blink") )

feature: Update eyeblink and smile View .... ussage( SmileView(ARstate: "blink") )

---

Ssok.xcodeproj/project.pbxproj
Ssok/AppDelegate.swift
Ssok/Model/What.swift
Ssok/Views/Ending/CameraEndingView.swift
Ssok/Views/MissionSmileView.swift

feature: add MissionSmileView

---

Ssok/Model/What.swift
Ssok/ViewModel/SpeechRecognizer.swift
Ssok/Views/Ending/SpeakEndingView.swift
Ssok/Views/SpeechView.swift
Ssok/Views/StrawView.swift

feature: bind speechview data

---

Ssok/Views/StrawView.swift

feature: add backbutton on strawview

feature: add backbutton on strawview

---

Ssok.xcodeproj/project.pbxproj
Ssok/Info.plist

feature: add info.plist

---

Ssok/Views/MissionSpeechView.swift
Ssok/Views/StrawView.swift

fix: fix progressview

---

Ssok.xcodeproj/project.pbxproj
Ssok/Model/What.swift
Ssok/ViewModel/Permission.swift
Ssok/Views/Ending/CameraEndingView.swift
Ssok/Views/MissionSmileView.swift

fix: camera dosen't come out when launch app first

fix: camera dosen't come out when launch app first

---

Ssok/Model/What.swift

docs: Remove remark

---

README.md

docs: fixed Image

---

Ssok/Views/MissionSmileView.swift
Ssok/Views/Recycle/MissionCameraCompleteView.swift

style: modify variable name

---

.swiftlint.yml
Ssok/AppDelegate.swift
Ssok/ViewModel/AddMemberViewModel.swift
Ssok/ViewModel/Permission.swift
Ssok/ViewModel/SpeechRecognizer.swift
Ssok/ViewModel/StrawViewModel.swift
Ssok/Views/BottleView.swift
Ssok/_BubblesApp.swift

refactor: apply swiftlint to BottleView

---

.swiftlint.yml
Ssok.xcodeproj/project.pbxproj
Ssok/ViewModel/BottleViewModel.swift
Ssok/Views/BottleView.swift
Ssok/Views/StrawView.swift

BottleView 없애고 BottleViewModel을 만들었고, StrawView에 SpriteView로 수정했습니다. 
일단 위치는 임의로 아무데나 배치를 해뒀고, 추후에 Lint 에러, 오류 다 잡은 후에 화면을 볼 수 있으면 그 때 수정하겠습니다.

refactor : refactoring BottleView

---

Ssok.xcodeproj/project.pbxproj
Ssok/ViewModel/BottleViewModel.swift
Ssok/Views/StrawView.swift

벽면 위치 다 수정했고, 속도가 이상했던 버그도 고쳤어요
StrawView에도 값 position 대신 offset으로 해놨어요

#92 BottleViewModel의 벽면 위치 수정

---

Ssok.xcodeproj/project.pbxproj
Ssok/AppDelegate.swift
Ssok/Model/NaviLink.swift
Ssok/Model/What.swift
Ssok/ViewModel/ARViewModel.swift
Ssok/ViewModel/BottleViewModel.swift
Ssok/ViewModel/GachaViewModel.swift
Ssok/ViewModel/NaviViewModel.swift
Ssok/Views/CameraView.swift
Ssok/Views/Ending/CameraEndingView.swift
Ssok/Views/Ending/MissionEndingView.swift
Ssok/Views/MissionSmileView.swift
Ssok/Views/Recycle/MissionCameraCompleteView.swift
Ssok/Views/Recycle/MissionCameraTopView.swift
Ssok/Views/StrawView.swift

Reverts DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#103

Revert "#99/change navigation to modal view"

---

Ssok/ViewModel/ARViewModel.swift
Ssok/Views/MissionSmileView.swift

refactor: ARkit viewmodel function name

refactor: ARkit viewmodel function name

---

Ssok/ViewModel/ARViewModel.swift
Ssok/Views/MissionSmileView.swift

Reverts DeveloperAcademy-POSTECH/MC2-Team8-5YearsOldGap#107

Revert "refactor: ARkit viewmodel function name"

---

Ssok.xcodeproj/project.pbxproj
Ssok/ViewModel/StrawViewModel.swift
Ssok/Views/StrawView.swift

- 작업한 브랜치 : #122 
- 음악 삭제
- StrawView Text 수정 및 Straw 사이즈 변경
```
func Ssok() -> String {
return "best"
}
```
- StrawView의 Straw가 다른 기기에서 비율이 이상해서 수정했습니다
- 
-
https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-Ssok/assets/54977093/8dd90ac3-e42a-4ccf-9979-8f97eafb3dfd
|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-Ssok/assets/54977093/8dd90ac3-e42a-4ccf-9979-8f97eafb3dfd" width = 40%>|
|:--:|
|StrawView|
- StrawView에서의 텍스트 수정
- MissionShakeView에서 음악 삭제
-
-
- 코드에 문제가 있거나 기능이 제대로 동작하지 않는다면 코멘트 달아주세요.
- 다른 문제도 언제든 환영합니다.

#122/modify pin

---

Ssok.xcodeproj/project.pbxproj
Ssok/Model/ARUnableDevices.swift
Ssok/Model/What.swift
Ssok/Views/MissionEndingView.swift

- 작업한 브랜치 : #129 
- 디바이스 기기 확인
- 아이폰 8 이하에서는 경고창 띄우기
```
func Ssok() -> String {
return "best"
}
```
|<img src = "">|
|:--:|
|MissionEndingView|
- 코드에 문제가 있거나 기능이 제대로 동작하지 않는다면 코멘트 달아주세요.
- 다른 문제도 언제든 환영합니다.

#129/feature add alert about AR

---

Ssok/Views/StrawView.swift

- 작업한 브랜치 : #131 
- 펄 문구 변경
- 빨대 꽂기로 변경
```
func Ssok() -> String {
return "best"
}
```
- 코드에 문제가 있거나 기능이 제대로 동작하지 않는다면 코멘트 달아주세요.
- 다른 문제도 언제든 환영합니다.

fix: change pearl and straw words

---

Ssok.xcodeproj/project.pbxproj

- 작업한 브랜치 : FixAppBundle
- App Bundle Identifier 변경
- 코드에 문제가 있거나 기능이 제대로 동작하지 않는다면 코멘트 달아주세요.
- 다른 문제도 언제든 환영합니다.

chore : Change App Bundle Identifier
